# Phony targets for easier dependencies
yahoo_clicklogs: $(BUILD)/clicklogs/yahoo_1m_perfect.clog
yahoo_clicklogs: $(BUILD)/clicklogs/yahoo_1m_position_eta_0.0.clog
yahoo_clicklogs: $(BUILD)/clicklogs/yahoo_1m_position_eta_0.5.clog
yahoo_clicklogs: $(BUILD)/clicklogs/yahoo_1m_position_eta_0.75.clog
yahoo_clicklogs: $(BUILD)/clicklogs/yahoo_1m_position_eta_1.0.clog
yahoo_clicklogs: $(BUILD)/clicklogs/yahoo_1m_position_eta_1.25.clog
yahoo_clicklogs: $(BUILD)/clicklogs/yahoo_1m_position_eta_1.5.clog
yahoo_clicklogs: $(BUILD)/clicklogs/yahoo_1m_position_eta_2.0.clog
yahoo_clicklogs: $(BUILD)/clicklogs/yahoo_1m_nearrandom_eta_1.0.clog
istella_clicklogs: $(BUILD)/clicklogs/istella_1m_perfect.clog
istella_clicklogs: $(BUILD)/clicklogs/istella_1m_position_eta_0.0.clog
istella_clicklogs: $(BUILD)/clicklogs/istella_1m_position_eta_0.5.clog
istella_clicklogs: $(BUILD)/clicklogs/istella_1m_position_eta_0.75.clog
istella_clicklogs: $(BUILD)/clicklogs/istella_1m_position_eta_1.0.clog
istella_clicklogs: $(BUILD)/clicklogs/istella_1m_position_eta_1.25.clog
istella_clicklogs: $(BUILD)/clicklogs/istella_1m_position_eta_1.5.clog
istella_clicklogs: $(BUILD)/clicklogs/istella_1m_position_eta_2.0.clog
istella_clicklogs: $(BUILD)/clicklogs/istella_1m_nearrandom_eta_1.0.clog
clicklogs: yahoo_clicklogs istella_clicklogs
.PHONY: clicklogs yahoo_clicklogs istella_clicklogs

# Click logs generated by baseline rankers
$(BUILD)/clicklogs/yahoo_1m_perfect.clog : $(BUILD)/baselines/yahoo.pth | $(BUILD)/clicklogs/
	python -m experiments.simulate_clicks --input_data $(YAHOO_DIR)/train.txt \
		--ranker $(BUILD)/baselines/yahoo.pth \
		--output_log $@.tmp \
		--sessions 10_000_000 \
		--max_clicks 1_000_000 \
		--behavior perfect
	mv $@.tmp $@

$(BUILD)/clicklogs/yahoo_1m_position_eta_0.0.clog : $(BUILD)/baselines/yahoo.pth | $(BUILD)/clicklogs/
	python -m experiments.simulate_clicks --input_data $(YAHOO_DIR)/train.txt \
		--ranker $(BUILD)/baselines/yahoo.pth \
		--output_log $@.tmp \
		--sessions 10_000_000 \
		--max_clicks 1_000_000 \
		--behavior position \
		--eta 0.0
	mv $@.tmp $@

$(BUILD)/clicklogs/yahoo_1m_position_eta_0.5.clog : $(BUILD)/baselines/yahoo.pth | $(BUILD)/clicklogs/
	python -m experiments.simulate_clicks --input_data $(YAHOO_DIR)/train.txt \
		--ranker $(BUILD)/baselines/yahoo.pth \
		--output_log $@.tmp \
		--sessions 10_000_000 \
		--max_clicks 1_000_000 \
		--behavior position \
		--eta 0.5
	mv $@.tmp $@

$(BUILD)/clicklogs/yahoo_1m_position_eta_0.75.clog : $(BUILD)/baselines/yahoo.pth | $(BUILD)/clicklogs/
	python -m experiments.simulate_clicks --input_data $(YAHOO_DIR)/train.txt \
		--ranker $(BUILD)/baselines/yahoo.pth \
		--output_log $@.tmp \
		--sessions 10_000_000 \
		--max_clicks 1_000_000 \
		--behavior position \
		--eta 0.75
	mv $@.tmp $@

$(BUILD)/clicklogs/yahoo_1m_position_eta_1.0.clog : $(BUILD)/baselines/yahoo.pth | $(BUILD)/clicklogs/
	python -m experiments.simulate_clicks --input_data $(YAHOO_DIR)/train.txt \
		--ranker $(BUILD)/baselines/yahoo.pth \
		--output_log $@.tmp \
		--sessions 10_000_000 \
		--max_clicks 1_000_000 \
		--behavior position \
		--eta 1.0
	mv $@.tmp $@

$(BUILD)/clicklogs/yahoo_1m_position_eta_1.25.clog : $(BUILD)/baselines/yahoo.pth | $(BUILD)/clicklogs/
	python -m experiments.simulate_clicks --input_data $(YAHOO_DIR)/train.txt \
		--ranker $(BUILD)/baselines/yahoo.pth \
		--output_log $@.tmp \
		--sessions 10_000_000 \
		--max_clicks 1_000_000 \
		--behavior position \
		--eta 1.25
	mv $@.tmp $@

$(BUILD)/clicklogs/yahoo_1m_position_eta_1.5.clog : $(BUILD)/baselines/yahoo.pth | $(BUILD)/clicklogs/
	python -m experiments.simulate_clicks --input_data $(YAHOO_DIR)/train.txt \
		--ranker $(BUILD)/baselines/yahoo.pth \
		--output_log $@.tmp \
		--sessions 10_000_000 \
		--max_clicks 1_000_000 \
		--behavior position \
		--eta 1.5
	mv $@.tmp $@

$(BUILD)/clicklogs/yahoo_1m_position_eta_2.0.clog : $(BUILD)/baselines/yahoo.pth | $(BUILD)/clicklogs/
	python -m experiments.simulate_clicks --input_data $(YAHOO_DIR)/train.txt \
		--ranker $(BUILD)/baselines/yahoo.pth \
		--output_log $@.tmp \
		--sessions 10_000_000 \
		--max_clicks 1_000_000 \
		--behavior position \
		--eta 2.0
	mv $@.tmp $@

$(BUILD)/clicklogs/yahoo_1m_nearrandom_eta_1.0.clog : $(BUILD)/baselines/yahoo.pth | $(BUILD)/clicklogs/
	python -m experiments.simulate_clicks --input_data $(YAHOO_DIR)/train.txt \
		--ranker $(BUILD)/baselines/yahoo.pth \
		--output_log $@.tmp \
		--sessions 10_000_000 \
		--max_clicks 1_000_000 \
		--behavior nearrandom \
		--eta 1.0
	mv $@.tmp $@

$(BUILD)/clicklogs/istella_1m_perfect.clog : $(BUILD)/baselines/istella.pth | $(BUILD)/clicklogs/
	python -m experiments.simulate_clicks --input_data $(ISTELLA_DIR)/train.txt \
		--ranker $(BUILD)/baselines/istella.pth \
		--output_log $@.tmp \
		--sessions 10_000_000 \
		--max_clicks 1_000_000 \
		--behavior perfect
	mv $@.tmp $@

$(BUILD)/clicklogs/istella_1m_position_eta_0.0.clog : $(BUILD)/baselines/istella.pth | $(BUILD)/clicklogs/
	python -m experiments.simulate_clicks --input_data $(ISTELLA_DIR)/train.txt \
		--ranker $(BUILD)/baselines/istella.pth \
		--output_log $@.tmp \
		--sessions 10_000_000 \
		--max_clicks 1_000_000 \
		--behavior position \
		--eta 0.0
	mv $@.tmp $@

$(BUILD)/clicklogs/istella_1m_position_eta_0.5.clog : $(BUILD)/baselines/istella.pth | $(BUILD)/clicklogs/
	python -m experiments.simulate_clicks --input_data $(ISTELLA_DIR)/train.txt \
		--ranker $(BUILD)/baselines/istella.pth \
		--output_log $@.tmp \
		--sessions 10_000_000 \
		--max_clicks 1_000_000 \
		--behavior position \
		--eta 0.5
	mv $@.tmp $@

$(BUILD)/clicklogs/istella_1m_position_eta_0.75.clog : $(BUILD)/baselines/istella.pth | $(BUILD)/clicklogs/
	python -m experiments.simulate_clicks --input_data $(ISTELLA_DIR)/train.txt \
		--ranker $(BUILD)/baselines/istella.pth \
		--output_log $@.tmp \
		--sessions 10_000_000 \
		--max_clicks 1_000_000 \
		--behavior position \
		--eta 0.75
	mv $@.tmp $@

$(BUILD)/clicklogs/istella_1m_position_eta_1.0.clog : $(BUILD)/baselines/istella.pth | $(BUILD)/clicklogs/
	python -m experiments.simulate_clicks --input_data $(ISTELLA_DIR)/train.txt \
		--ranker $(BUILD)/baselines/istella.pth \
		--output_log $@.tmp \
		--sessions 10_000_000 \
		--max_clicks 1_000_000 \
		--behavior position \
		--eta 1.0
	mv $@.tmp $@

$(BUILD)/clicklogs/istella_1m_position_eta_1.25.clog : $(BUILD)/baselines/istella.pth | $(BUILD)/clicklogs/
	python -m experiments.simulate_clicks --input_data $(ISTELLA_DIR)/train.txt \
		--ranker $(BUILD)/baselines/istella.pth \
		--output_log $@.tmp \
		--sessions 10_000_000 \
		--max_clicks 1_000_000 \
		--behavior position \
		--eta 1.25
	mv $@.tmp $@

$(BUILD)/clicklogs/istella_1m_position_eta_1.5.clog : $(BUILD)/baselines/istella.pth | $(BUILD)/clicklogs/
	python -m experiments.simulate_clicks --input_data $(ISTELLA_DIR)/train.txt \
		--ranker $(BUILD)/baselines/istella.pth \
		--output_log $@.tmp \
		--sessions 10_000_000 \
		--max_clicks 1_000_000 \
		--behavior position \
		--eta 1.5
	mv $@.tmp $@

$(BUILD)/clicklogs/istella_1m_position_eta_2.0.clog : $(BUILD)/baselines/istella.pth | $(BUILD)/clicklogs/
	python -m experiments.simulate_clicks --input_data $(ISTELLA_DIR)/train.txt \
		--ranker $(BUILD)/baselines/istella.pth \
		--output_log $@.tmp \
		--sessions 10_000_000 \
		--max_clicks 1_000_000 \
		--behavior position \
		--eta 2.0
	mv $@.tmp $@

$(BUILD)/clicklogs/istella_1m_nearrandom_eta_1.0.clog : $(BUILD)/baselines/istella.pth | $(BUILD)/clicklogs/
	python -m experiments.simulate_clicks --input_data $(ISTELLA_DIR)/train.txt \
		--ranker $(BUILD)/baselines/istella.pth \
		--output_log $@.tmp \
		--sessions 10_000_000 \
		--max_clicks 1_000_000 \
		--behavior nearrandom \
		--eta 1.0
	mv $@.tmp $@
