# Variables, customize to your environment
YAHOO_DIR := /Users/rolfjagerman/Datasets/Yahoo/set1
BUILD := build

# Default is to run the entire experimental pipeline
.PHONY: all
all: $(BUILD)/baselines/yahoo.pth

# Baseline rankers trained on fractions of data
$(BUILD)/baselines/yahoo.pth : | $(BUILD)/baselines/
	python -m experiments.baseline --train_data $(YAHOO_DIR)/train.txt --output $(BUILD)/baselines/yahoo.pth --optimizer sgd --lr 0.0001 --fraction 0.01

$(BUILD)/baselines/ :
	mkdir -p $(BUILD)/baselines/


# Click logs generated by baseline rankers
$(BUILD)/clicklogs/yahoo_perfect_1000000.clog : $(BUILD)/baselines/yahoo.pth | $(BUILD)/clicklogs/
	python -m experiments.simulate_clicks --input_data $(YAHOO_DIR)/train.txt \
		--ranker $(BUILD)/baselines/yahoo.pth \
		--output_log $@ \
		--sessions 2_000_000 \
		--max_clicks 1_000_000 \
		--behavior perfect

$(BUILD)/clicklogs/yahoo_position_1000000.clog : $(BUILD)/baselines/yahoo.pth | $(BUILD)/clicklogs/
	python -m experiments.simulate_clicks --input_data $(YAHOO_DIR)/train.txt \
		--ranker $(BUILD)/baselines/yahoo.pth \
		--output_log $@ \
		--sessions 2_000_000 \
		--max_clicks 1_000_000 \
		--behavior position \
		--eta 1.0 \
		--pos_prob 1.0 \
		--neg_prob 0.1

$(BUILD)/clicklogs/yahoo_nearrandom_1000000.clog : $(BUILD)/baselines/yahoo.pth | $(BUILD)/clicklogs/
	python -m experiments.simulate_clicks --input_data $(YAHOO_DIR)/train.txt \
		--ranker $(BUILD)/baselines/yahoo.pth \
		--output_log $@ \
		--sessions 2_000_000 \
		--max_clicks 1_000_000 \
		--behavior nearrandom \
		--eta 1.0

$(BUILD)/clicklogs/ :
	mkdir -p $(BUILD)/clicklogs/
